linters:
  enable-all: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - scopelint
      text: Using the variable on range scope `(tc|tt)` in function literal

    # For golden file
    - path: (file|integration)_test\.go
      linters:
        - gochecknoglobals
      text: "`update` is a global variable"
