linters:
  enable-all: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - scopelint
      text: Using the variable on range scope `(tc|tt)` in function literal

    # For golden file
    - path: (file|integration)_test\.go
      linters:
        - gochecknoglobals
      text: "`update` is a global variable"

    # Usually we have table driven tests which make the test function too long.
    - path: _test\.go
      linters:
        - funlen
      text: Function '.+' is too long
