run:
  build-tags:
    - integration

linters:
  enable-all: true

issues:
  exclude-rules:
    # Usually we have table driven tests which make the test function too long.
    - path: _test\.go
      linters:
        - funlen
      text: Function '.+' is too long

    # A long URL
    - path: internal/file/sort.go
      linters:
        - lll
      text: "line is 146 characters"
