before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - windows
      - linux
    ldflags:
      - -s -w -X main.version={{.Version}}
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64

brews:
  - tap:
      owner: shihanng
      name: homebrew-gig
    commit_author:
      name: "Shi Han NG"
      email: shihanng@gmail.com
    description: "gitignore file generator"
    homepage: "https://github.com/shihanng/gig"
    dependencies:
      - fzf
    install: |
      bin.install Dir['gig']
    test: |
      system "#{bin}/gig"

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  skip: true
